spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
